fragment Page on TemplatePageRecord {
  id
  slug
  components {
    ...Switchback
    ...ProjectListing
    ...Carousel
    ...ScrollingSwitchback
    ...BlogListing
    ...SingleUseComponent
    ...FeatureHighlight
  }
  seo {
    description
    title
    image {
      ...Image
    }
  }
}

query AllTemplatePageSlugs {
  allTemplatePages {
    slug
  }
}

query TemplatePage($slug: String) {
  templatePage(filter: { slug: { eq: $slug } }) {
    ...Page
  }
}

query TemplatePageMetadata($slug: String) {
  metaData: templatePage(filter: { slug: { eq: $slug } }) {
    id
    seo {
      description
      title
      image {
        ...Image
      }
    }
  }
}
