fragment ProjectCard on ProjectRecord {
  title
  subtitle
  slug
  excerpt {
    value
    links
  }
  techStack {
    ...TechStack
  }
  bannerImage {
    ...Image
  }
}

fragment ProjectListing on ProjectListingRecord {
  id
  heading
  headingAs
  sectionId
  bgColor
  body {
    value
  }
  cards {
    ...ProjectCard
  }
}
