fragment Project on TemplateProjectRecord {
  id
  slug
  title
  subtitle
  heading
  body {
    value
    links {
      ...Button
    }
  }
  extraInformation {
    value
    links {
      ...Button
    }
  }
  bannerImage {
    ...Image
  }
  techStack {
    ...TechStack
  }
  switchbacks {
    ...ScrollingSwitchback
  }
}

query AllProjectSlugs {
  allSlugs: allTemplateProjects {
    slug
  }
}

query ProjectPage($slug: String!) {
  templateProject(filter: { slug: { eq: $slug } }) {
    ...Project
  }
  templatePage(filter: { slug: { eq: "home" } }) {
    components {
      ...ProjectListing
    }
  }
}

query ProjectPageMetadata($slug: String!) {
  metaData: templateProject(filter: { slug: { eq: $slug } }) {
    id
    seo {
      title
      description
      image {
        ...Image
      }
    }
  }
}
