fragment Blog on TemplateBlogPostRecord {
  id
  internalName
  title
  subtitle
  publishDate
  categories {
    ...Category
  }
  slug
  body {
    value
    links {
      ...Button
    }
    blocks {
      id
      media {
        title
        __typename
        id
        alt
        blurhash
        height
        width
        url
      }
    }
  }
  featuredImage {
    ...Image
  }
}

query TemplateBlogPost($slug: String!) {
  templateBlogPost(filter: { slug: { eq: $slug } }) {
    ...Blog
  }
}

query AllBlogPostSlugs {
  allTemplateBlogPosts {
    slug
  }
}

query BlogMetaData($slug: String!) {
  blogMetaData: templateBlogPost(filter: { slug: { eq: $slug } }) {
    id
    title
    publishDate
    seo {
      description
      title
      image {
        ...Image
      }
    }
  }
}
