fragment Image on FileField {
  id
  alt
  blurhash
  height
  width
  url
}

fragment Company on CompanyRecord {
  name
  logo {
    ...Image
  }
  website
}

fragment Person on PersonRecord {
  firstName
  lastName
  role
  thumbnail {
    ...Image
  }
  company {
    ...Company
  }
  website
}

fragment Category on CategoryRecord {
  name
  slug
}
