fragment Page on TemplatePageRecord {
  id
  slug
  components {
    ...Switchback
    ...ProjectListing
    ...Carousel
    ...ScrollingSwitchback
    ...BlogListing
    ...SingleUseComponent
    ...FeatureHighlight
  }
  seo {
    description
    title
    image {
      ...Image
    }
  }
}

query AllTemplatePageSlugs {
  allTemplatePages {
    slug
  }
}

query templatePage($slug: String) {
  templatePage(filter: { slug: { eq: $slug } }) {
    ...Page
  }
}
