name: CICD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NEXT_PUBLIC_DATO_CMS: ${{ secrets.NEXT_PUBLIC_DATO_CMS }}

defaults:
  run:
    working-directory: ./

jobs:
  check:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: "use node ${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint check
        run: yarn lint

      - name: Format check
        run: yarn prettier

      - name: Unit & Integration tests
        run: yarn test

  semantic-release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: ["check"]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: "yarn"

      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: yarn --frozen-lockfile

      - name: "Build package"
        run: yarn build

      - name: "Release"
        id: "release"
        uses: codfish/semantic-release-action@v2.2.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
